[versions]
adaptiveVersion = "1.0.0-rc01"
filekitComposeVersion = "0.8.7"
hypnoticcanvas = "0.4.0"
kotlinx-serialization-json-version = "1.7.3"
material3WindowSizeClassVersion = "1.7.0"
navigation-compose-version = "2.8.0-alpha10"
lifecycle-viewmodel-compose-version = "2.8.2"
kotlin-version = "2.2.21"
agp-version = "8.12.3"
compose-version = "1.10.0-beta01"
kotlinx-datetime = "0.6.1"
precompose = "1.6.0"
datastore-version = "1.1.1"
materialKolor = "2.0.0"
colorpickerCompose = "1.1.2"
ksp = "2.3.1"
androidx-room = "2.8.3"
uiVersion = "0.1.5"
kstore = "0.8.0"
sqlite = "2.6.1"
kotlinx-coroutines-core = "1.9.0"
appVersion = "6.0.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp-version" }
android-library = { id = "com.android.library", version.ref = "agp-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidx-room" }

[libraries]
adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptiveVersion" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.15.0" }
androidx-activity-compose = "androidx.activity:activity-compose:1.9.3"
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekitComposeVersion" }
hypnoticcanvas = { module = "com.mikepenz.hypnoticcanvas:hypnoticcanvas", version.ref = "hypnoticcanvas" }
hypnoticcanvas-shaders = { module = "com.mikepenz.hypnoticcanvas:hypnoticcanvas-shaders", version.ref = "hypnoticcanvas" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json-version" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose-version" }
material3-window-size = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClassVersion" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose-version" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore-version" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore-version" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpickerCompose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-sqlite = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines-core" }
krop-ui = { module = "com.attafitamim.krop:ui", version.ref = "uiVersion" }

kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }
kstore-storage = { module = "io.github.xxfast:kstore-storage", version.ref = "kstore" }